export const majors = [
  // Humanities
  'Others',
  'American Studies',
  'Ancient History',
  'Anthropology',
  'Archaeology',
  'Art History',
  'Asian Studies',
  'Classical Studies',
  'Comparative Literature',
  'Creative Writing',
  'Cultural Studies',
  'East Asian Languages and Cultures',
  'English Literature',
  'European Studies',
  'Folklore',
  'Gender and Sexuality Studies',
  'History of Science',
  'International Studies',
  'Islamic Studies',
  'Jewish Studies',
  'Latin American Studies',
  'Linguistics',
  'Middle Eastern Studies',
  'Philosophy',
  'Religious Studies',
  'South Asian Studies',
  'Translation Studies',
  'Visual and Media Studies',
  'Writing and Rhetoric',

  // Social Sciences
  'African American Studies',
  'Arms Control and Disarmament',
  'Behavioral Science',
  'Communication Studies',
  'Criminal Justice',
  'Criminology',
  'Demography',
  'Development Studies',
  'Diplomacy and International Relations',
  'Econometrics',
  'Education',
  'Environmental Policy',
  'Ethnic Studies',
  'Geography',
  'Government',
  'Human Rights',
  'International Development',
  'Labor Studies',
  'Law',
  'Peace and Conflict Studies',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Public Policy',
  'Social Work',
  'Sociology',
  'Urban Studies',
  'Women’s Studies',

  // Natural Sciences
  'Agricultural Science',
  'Astronomy',
  'Astrophysics',
  'Atmospheric Science',
  'Biochemistry',
  'Biology',
  'Botany',
  'Cell Biology',
  'Chemical Biology',
  'Chemistry',
  'Earth Science',
  'Ecology',
  'Environmental Science',
  'Forensic Science',
  'Genetics',
  'Geology',
  'Marine Biology',
  'Materials Science',
  'Meteorology',
  'Microbiology',
  'Molecular Biology',
  'Nanoscience',
  'Neuroscience',
  'Oceanography',
  'Paleontology',
  'Physics',
  'Plant Science',
  'Quantum Mechanics',
  'Soil Science',
  'Space Science',
  'Statistics',
  'Zoology',

  // Engineering and Technology
  'Aerospace Engineering',
  'Agricultural Engineering',
  'Automotive Engineering',
  'Bioengineering',
  'Biomedical Engineering',
  'Chemical Engineering',
  'Civil Engineering',
  'Computer Engineering',
  'Computer Science',
  'Cybersecurity',
  'Data Science',
  'Electrical Engineering',
  'Environmental Engineering',
  'Genetic Engineering',
  'Geological Engineering',
  'Industrial Engineering',
  'Information Systems',
  'Information Technology',
  'Manufacturing Engineering',
  'Marine Engineering',
  'Materials Engineering',
  'Mechanical Engineering',
  'Mining Engineering',
  'Nanotechnology',
  'Nuclear Engineering',
  'Petroleum Engineering',
  'Robotics',
  'Software Engineering',
  'Systems Engineering',
  'Telecommunications Engineering',

  // Health and Medicine
  'Anatomy',
  'Anesthesiology',
  'Biostatistics',
  'Chiropractic Medicine',
  'Clinical Laboratory Science',
  'Dentistry',
  'Dietetics',
  'Emergency Medicine',
  'Epidemiology',
  'Exercise Science',
  'Genetic Counseling',
  'Gerontology',
  'Global Health',
  'Health Information Management',
  'Health Policy',
  'Kinesiology',
  'Medical Imaging',
  'Medical Laboratory Science',
  'Medicine',
  'Nursing',
  'Nutrition Science',
  'Occupational Therapy',
  'Oncology',
  'Optometry',
  'Orthopedics',
  'Pharmaceutical Science',
  'Pharmacy',
  'Physical Therapy',
  'Physician Assistant Studies',
  'Public Health',
  'Radiologic Technology',
  'Rehabilitation Science',
  'Respiratory Therapy',
  'Sports Medicine',
  'Surgery',
  'Veterinary Medicine',

  // Business and Economics
  'Accounting',
  'Actuarial Science',
  'Advertising',
  'Business Analytics',
  'Business Administration',
  'Commercial Law',
  'Consumer Behavior',
  'E-commerce',
  'Entrepreneurship',
  'Finance',
  'Human Resource Management',
  'International Business',
  'Investment Banking',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Operations Management',
  'Organizational Behavior',
  'Public Relations',
  'Real Estate',
  'Risk Management',
  'Supply Chain Management',
  'Tourism and Hospitality Management',

  // Fine Arts and Design
  'Animation',
  'Architecture',
  'Ceramics',
  'Dance',
  'Fashion Design',
  'Film Studies',
  'Fine Arts',
  'Graphic Design',
  'Industrial Design',
  'Interior Design',
  'Jewelry Design',
  'Music Composition',
  'Music Performance',
  'Painting',
  'Photography',
  'Printmaking',
  'Sculpture',
  'Theater',
  'Visual Arts',

  // Environmental and Sustainability Studies
  'Climate Science',
  'Conservation Biology',
  'Energy Resources',
  'Environmental Management',
  'Environmental Policy',
  'Forestry',
  'Natural Resources Management',
  'Sustainable Agriculture',
  'Sustainable Development',
  'Urban Ecology',
  'Water Resources Management',
  'Wildlife Conservation'
];
