export const peopleData = [
  // 중국 (10명)
  {
    univcert: false,
    email: 'user1@example.com',
    password: 'password123',
    nickname: 'nickname1',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2010-01-15T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user2@example.com',
    password: 'password123',
    nickname: 'nickname2',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2012-03-18T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user3@example.com',
    password: 'password123',
    nickname: 'nickname3',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2014-07-10T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user4@example.com',
    password: 'password123',
    nickname: 'nickname4',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2016-11-23T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user5@example.com',
    password: 'password123',
    nickname: 'nickname5',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2018-02-05T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user6@example.com',
    password: 'password123',
    nickname: 'nickname6',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2020-09-09T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user7@example.com',
    password: 'password123',
    nickname: 'nickname7',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2021-12-01T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user8@example.com',
    password: 'password123',
    nickname: 'nickname8',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2019-06-15T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user9@example.com',
    password: 'password123',
    nickname: 'nickname9',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2015-03-11T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user10@example.com',
    password: 'password123',
    nickname: 'nickname10',
    major: 'Others',
    nationality: 'China',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2013-08-25T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },

  // 캐나다 (10명)
  {
    univcert: false,
    email: 'user11@example.com',
    password: 'password123',
    nickname: 'nickname11',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2017-04-12T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user12@example.com',
    password: 'password123',
    nickname: 'nickname12',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2019-11-07T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user13@example.com',
    password: 'password123',
    nickname: 'nickname13',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2020-01-29T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user14@example.com',
    password: 'password123',
    nickname: 'nickname14',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2018-10-18T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user15@example.com',
    password: 'password123',
    nickname: 'nickname15',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2016-05-04T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user16@example.com',
    password: 'password123',
    nickname: 'nickname16',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2014-12-20T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user17@example.com',
    password: 'password123',
    nickname: 'nickname17',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2015-07-19T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user18@example.com',
    password: 'password123',
    nickname: 'nickname18',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2013-09-03T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user19@example.com',
    password: 'password123',
    nickname: 'nickname19',
    major: 'Others',
    nationality: 'Canada',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2012-03-15T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user21@example.com',
    password: 'password123',
    nickname: 'nickname21',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2011-09-25T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user22@example.com',
    password: 'password123',
    nickname: 'nickname22',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2013-11-12T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user23@example.com',
    password: 'password123',
    nickname: 'nickname23',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2015-04-08T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user24@example.com',
    password: 'password123',
    nickname: 'nickname24',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2016-06-22T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user25@example.com',
    password: 'password123',
    nickname: 'nickname25',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2017-08-15T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user26@example.com',
    password: 'password123',
    nickname: 'nickname26',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2018-10-30T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user27@example.com',
    password: 'password123',
    nickname: 'nickname27',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2019-12-01T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user28@example.com',
    password: 'password123',
    nickname: 'nickname28',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2020-02-11T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user29@example.com',
    password: 'password123',
    nickname: 'nickname29',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2021-05-17T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user30@example.com',
    password: 'password123',
    nickname: 'nickname30',
    major: 'Others',
    nationality: 'United States',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2022-07-25T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user31@example.com',
    password: 'password123',
    nickname: 'nickname31',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2012-01-14T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user32@example.com',
    password: 'password123',
    nickname: 'nickname32',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2014-05-17T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user33@example.com',
    password: 'password123',
    nickname: 'nickname33',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2015-09-09T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user34@example.com',
    password: 'password123',
    nickname: 'nickname34',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2016-12-13T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user35@example.com',
    password: 'password123',
    nickname: 'nickname35',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2018-03-27T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user36@example.com',
    password: 'password123',
    nickname: 'nickname36',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2019-07-02T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user37@example.com',
    password: 'password123',
    nickname: 'nickname37',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2020-10-19T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  },
  {
    univcert: false,
    email: 'user38@example.com',
    password: 'password123',
    nickname: 'nickname38',
    major: 'Others',
    nationality: 'Russia',
    sex: null,
    birth: null,
    languages: 'English',
    introduce: "Hello, I'm a student!",
    mbti: null,
    profile_image: null,
    univ_certified: false,
    created_at: '2021-01-11T00:00:00',
    is_staff: false,
    start_date: '',
    end_date: ''
  }
];
